version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm run dev -- --host"
