version: "3.8"

services:
  user-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - user-db

  user-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - user-data:/var/lib/postgresql/data

volumes:
  user-data:
